source 'https://github.com/CocoaPods/Specs.git'

target 'KPCalendar', :exclusive => true do
  pod "KPCalendar", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "KPCalendar", :path => "../"

  
end
